INSERT INTO CPS_USUARIO (ID,NOME,LOGIN,SENHA,EMAIL) VALUES (1,'caio', 'cps405','123456','cps@gmail.com');

ALTER SEQUENCE CPS_USUARIO_ID_SEQ RESTART with 2;

INSERT INTO CPS_PERFIL (ID,DESCRICAO) VALUES (1,'dev');

ALTER SEQUENCE CPS_PERFIL_SEQ RESTART with 2;

INSERT INTO CPS_RECURSO (ID,NOME,CHAVE) VALUES (1,'tela Usuário', 'usuario');

ALTER SEQUENCE CPS_RECURSO_SEQ RESTART with 2;